POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Unite Summit",
    "details": "evento para quem é apaixonado por programação",
    "maximumAttendees": 30
}

###

POST http://localhost:3333/events/12d1dd79-48ed-4656-9ce5-61828fc7cb86/attendees
Content-Type: application/json

{
    "name": "Leonardo Souza",
    "email": "leonardo.souza@email.com"
}

###

GET http://localhost:3333/events/12d1dd79-48ed-4656-9ce5-61828fc7cb86

###

GET http://localhost:3333/attendees/10/badge

###

GET http://localhost:3333/attendees/21/check-in


###

GET http://localhost:3333/events/12d1dd79-48ed-4656-9ce5-61828fc7cb86/attendees?query=leonardo